---
title: "04-03-Calibration-Application-Tool"
author: "Michael Arbeider"
date: "2026-03-06"
---

# Set-up
## Packages
```{r}
#rm(list = ls())
library(readxl) # read_excel
library(tidyverse) # most %>% 
theme_set(theme_bw()) # ggplot
library(patchwork) # for multi plot ggplot graphs
library(scales) # for label_comma()
library(stringr) # str_extract
source("00-Functions.R") # scale_x_reordered, rank.summary(), round2()
library(tidyhydat) # hy_daily for hydrometric data
cal_4apply <- readRDS("./r_objects/03_cal_4apply.rds")
mods <- readRDS("./r_objects/03_mods.rds")
mod.spec.fn <- readRDS("./r_objects/03_mod_spec_fn.rds")
mod.specs <- readRDS("./r_objects/models/model_specifications.rds")
```

# Data
# Model Selection Results
Reading in the model selection results.
```{r}
mod.selection <- readRDS(file = "./r_objects/02_01_rank_top_results.rds")
mod.selection <- filter(mod.selection,
                        keep == TRUE)

mod.selection$rank.filter[mod.selection$rank.filter == "O' Ne-Ell Creek"] <- "O'Ne-ell Creek"

# Method, Size, Clarity
lpe.ranges.msc <- readRDS("./r_objects/00-Regression_LPE_Ranges_Clarity_Method.rds") %>% 
  dplyr::select(-n)

# Method Size
lpe.ranges.ms <- lpe.ranges.msc %>% 
  group_by(lpe_method, size) %>% 
  summarize(min10.ms = min(min10),
            max10.ms = max(max10))

# Method Aggregate
lpe.ranges.ma <- lpe.ranges.msc %>% 
  mutate(aggr = case_when(
    size %in% c("Large", "X-Large") ~ "LXL",
    size %in% c("Small", "Medium") ~ "SM"
  )) %>% 
  group_by(lpe_method, aggr) %>% 
  summarize(min10.ma = min(min10),
            max10.ma = max(max10))
```

## 2024 Data
```{r}
cal.input <-read_excel("./data/calibration_input_2024.xlsx", sheet="Calibration_Input",
                     na = c("", "NA"))   
glimpse(cal.input)

ec.stations <- read.csv("./data/ec_stations_clean.csv")
glimpse(ec.stations)
```

### Cleaning and Joining
```{r}
# re-labelling water clarities to only two bins
# # re-labelling Very Small to Small.
cal.input <- cal.input %>% 
  mutate(lpe_method = case_when(
    lpe_method %in% c("Aerial", "Ground") ~ lpe_method,
    !lpe_method %in% c("Aerial", "Ground") ~ "Ground"
  ),
         lpe = case_when(
    lpe_method=="Aerial" & !is.na(aerial_unsexed_above) ~ peak_live_above + 
      aerial_unsexed_above,
    lpe_method=="Aerial" & is.na(aerial_unsexed_above) ~ peak_live_above,
    lpe_method=="Ground" & !is.na(ground_cuml_carc_above) ~ peak_live_above + 
      ground_cuml_carc_above,
    lpe_method=="Ground" & is.na(ground_cuml_carc_above) ~ peak_live_above
    ),
    water_clarity = 
           ifelse(water_clarity == "Clear", "Clear", "Pt_Turb_Tannic"),
         size = as.character(size),
         size = 
           ifelse(size == "V. Small", "Small", size),
         size = as.factor(size),
  substrate_shade = as.factor(substrate_shade),
         aggr = ifelse(size %in% c("Large", "X-Large"), "LXL", "SM")) %>% 
  left_join(., ec.stations) %>% 
  left_join(., lpe.ranges.ms) %>% 
  left_join(., lpe.ranges.ma) %>% 
  mutate(is.less.than = lpe < min10.ms,
         is.greater.than = lpe > max10.ma)
```

#### Discharge
```{r}
cal.flow <- hy_daily_flows(station_number = ec.stations$ec_station_number,
                           start_date = "2024-01-01") %>% 
  rename(lpe_date = Date, ec_station_number = STATION_NUMBER)

cal.input %>% 
  dplyr::select(lpe_date, gazetted_stream_name, ec_station_number) %>% 
  filter(!is.na(ec_station_number)) %>% 
  left_join(., cal.flow)
# If any Flows are NA - then need to look them up manually because they haven't been uploaded to the database yet.
# https://wateroffice.ec.gc.ca/mainmenu/real_time_data_index_e.html
 
cal.input <- cal.input %>% 
  left_join(., cal.flow) %>% 
  mutate(water_discharge = Value)
```

```{r}
# making an output dataframe for the resulting calibrated estimates
cal.out <- dplyr::select(cal.input,
                         watershed_group:year,size,aggr, lpe_method, 
                         water_clarity, substrate_shade, lpe, 
                         estimate_method:RSA_reason, min10.ms,
                         is.less.than, max10.ma, is.greater.than) %>% 
  mutate(default = lpe*1.8,
         calibration.model = NA,
         fit = NA, 
         se.fit = NA,
         fit.cv = NA,
         calibrated.se.lower = NA,
         calibrated.se.upper = NA,
         calibrated.estimate = NA)
```

## Model Application
```{r}
# for each row in the data that needs calibrating
for(i in 1:nrow(cal.input)){
  cal.lp <- cal.input[i, ] # pull out the first row
  # lp == loop
  lp.method <- as.character(cal.lp$lpe_method) # identify its survey method
  lp.sys <- cal.lp$gazetted_stream_name
  lp.size = as.character(cal.lp$size)
  lp.agg <- ifelse(lp.size %in% c("Large", "X-Large"), "LXL", "SM") # is the system X-Large?
  lp.size.clarity <- paste0(lp.size, "_", cal.lp$water_clarity)
  lp.system.method = paste0(cal.lp$gazetted_stream_name, "_", lp.method)
  
  # pulling out the various models that may be applied to the system
  mod.lp <- mod.selection %>% 
    filter(rank.method == lp.method,
           rank.filter %in% c(lp.sys,
                              lp.size.clarity,
                              lp.size,
                              lp.agg,
                              "All")) %>% 
    arrange(desc(special.level)) # arranged from highest to lowest
  # note that there will be multiple models in most cases.
  # The following code sets up a loop to apply each model starting with the
  # highest ranked model. Once a result is produced, the loop stops trying to
  # apply the subsequent models. i.e. the "most specialized" model is applied
  # and the more general models are only applied if a covariate is missing to be
  # used with the more specialized models
  
  # Is it less than the training data range?
  # If YES, then apply expert-decision rules
  if(cal.lp$is.less.than == TRUE){
    # depending if the top model is the early stuart model or not
    if(mod.lp$top.model[1] != "Early_Stu_DeadAlive_Model")mod.lp$top.model = "MoR_Low_Abundance_Models" # force use of Clarity GLM for all
    if(mod.lp$top.model[1] == "Early_Stu_DeadAlive_Model")mod.lp$top.model[c(2:nrow(mod.lp))] = "MoR_Low_Abundance_Models" # force use of Clarity GLM only after testing if data is available to run Early Stuart Model
  }
  
  
  # Is it greater than the training data range?
  # If YES, then apply expert-decision rules
    if(cal.lp$is.greater.than == TRUE & cal.lp$lpe_method == "Ground"){
    mod.lp$top.model = "All_ROM_Gen_Model" # force use of Minimal GLM
  }
    if(cal.lp$is.greater.than == TRUE & cal.lp$lpe_method == "Aerial"){
    mod.lp$top.model = "All_ROM_GenB_Model" # force use of Minimal GLM
  }
  
  result.flag = TRUE # resetting result.flag for each estimate prior entering the next loop
  
  for(j in 1:nrow(mod.lp)){# start of j loop
    if(result.flag == TRUE){ # start of result.flag statement 1
      top.model.name <- mod.lp$top.model[j]
      is.individual <- str_detect(top.model.name, "Individual")
      
      # if it is the individual model, need to select which individual model it is in addition to the data
     if(is.individual == TRUE){
       ## NOTE - all these try and tests really slow things down unfortunately
      test <- try(mod.spec.fn[[top.model.name]](cal.lp, lp.system.method), silent = T) # test if the model can be applied
      if('try-error' %in% class(test)) { # if there is an error then
        result.flag = TRUE # ping the result flag, which will trigger running the next iteration of the j loop
      } else { # if it is not an error, then the model will run
          cal.lp = mod.spec.fn[[top.model.name]](cal.lp, lp.system.method)
        } # end of is.individual test
      } else { # just need to select the data if it is not an individual model
        test <- try(mod.spec.fn[[top.model.name]](cal.lp), silent = T) # test if the model can be applied
        if('try-error' %in% class(test)) { # if there is an error then
        result.flag = TRUE # ping the result flag, which will trigger running the next iteration of the j loop
      } else { # if it is not an error, then the model will run
          cal.lp = mod.spec.fn[[top.model.name]](cal.lp)
        } # end of 2nd test
    } # end of model application
    # check if the fit produced a result, possibly not due to not having all of the covariates
      if("fit" %in% names(cal.lp)) { # if a fit was produced, then a new column named fit will exist
        result.flag = ifelse(is.na(cal.lp$fit), TRUE, FALSE) # the result flag only is turned off if fit is also not NA
      } else {
          result.flag = TRUE # otherwise, the result flag stays on
          }
    # if result.flag == FALSE, then an estimate was produced.
    if(result.flag == FALSE) { # start of result.flag statement 2
      cal.out$calibration.model[i] = top.model.name
      cal.out$fit[i] = cal.lp$fit
      cal.out$se.fit[i] = cal.lp$se.fit
      cal.out$fit.cv[i] = cal.lp$fit.cv
      cal.out$calibrated.se.lower[i] = cal.lp$calibrated.se.lower
      cal.out$calibrated.se.upper[i] = cal.lp$calibrated.se.upper
      cal.out$calibrated.estimate[i] = cal.lp$calibrated.estimate
      } # end of result.flag statement 2
    }# end of result.flag statement 1
  }# end of j loop for nrow(mod.lp)
  print(c(i, top.model.name, cal.lp$gazetted_stream_name))
  # clear temporary loop files
  rm(cal.lp, top.model.name, lp.sys, lp.method, lp.size, 
     lp.size.clarity, lp.agg, lp.system.method, test)
} # end of i loop of calibration data set
```

```{r}
cal.out <- filter(cal.out, !is.na(calibrated.estimate)) %>% 
  mutate(calibrated.estimate = round2(calibrated.estimate, 1),
         default.per.diff = (calibrated.estimate - default) / default,
         RSA.per.diff = (calibrated.estimate - RSA) / RSA,
         RSA.applied = ifelse(is.na(RSA_reason), "No", "Yes"))

# any NAs?
cal.out.na <- filter(cal.out, is.na(n))

saveRDS(cal.out, "./r_objects/04_03_2024_Calibration_wDecisionRules.rds")
write.csv(cal.out, "./tables/04_03_2024_Calibration_wDecisionRules.csv", row.names = F)
```

```{r}
# ---- 4) Parametric bootstrap for 95% CI ----
set.seed(123)
N <- 200000

transformation <- mod.specs %>% 
  filter(target %in% c(NA, "lpe"),
         order %in% c(NA, 1)) %>% 
  mutate(type = ifelse(is.na(type), "linear", type)) %>% 
  dplyr::select(model, type) %>% 
  rename(calibration.model = model) %>% 
  rbind(., data.frame(calibration.model = "All_ROM_GenB_Model",
                      type = "log"))

cal.out <- left_join(cal.out, transformation) %>% 
  filter(estimate_method == "(Peak Live + Cumulative Dead)*Expansion")

# Generate draws component-wise then sum (fast and memory-safe approach)
sum_draws <- rep(0, N)
for (i in seq_len(nrow(cal.out))) {
  tr <- cal.out$type[i]
  mu <- cal.out$fit[i]
  s  <- cal.out$se.fit[i]
  if (tr == "linear" || is.na(tr)) {
    draws <- rnorm(N, mean=mu, sd=s)
  } else if (tr == "log") {
    draws <- exp(rnorm(N, mean=mu, sd=s))
  } else if (tr == "cube") {
    draws <- rnorm(N, mean=mu, sd=s)^3 
  } else {
    draws <- rep(0, N)
  }
  sum_draws <- sum_draws + draws
}

ci_boot <- quantile(sum_draws, c(0.025, 0.975))
boot_median <- quantile(sum_draws, 0.5)
raw_total <- sum(cal.out$calibrated.estimate)

cat(sprintf("Raw mean: %.3f\n", raw_total))
cat(sprintf("Bootstrap mean: %.3f\n", boot_median))
cat(sprintf("Bootstrap 95%% CI: [%.3f, %.3f]\n", ci_boot[1], ci_boot[2]))

```

